### ISSUE TITLE
Baskerville project

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/arc-selective-forgetting#6]
Request one (try to get at least a rough idea of how much compute we might need first)

**Comment by philswatton** [comment]
Compute will be a rough function of:

- N. of experiments (each will involve two models: the full model and the counterfactual model). Our experiments will (mostly) involve variations in the dataset to be forgotten
- Size of dataset (less impact from this)
- Size of model
- Whether we are using PEFT

It's also likely we'll use Baskerville for the following:
- Unlearning techniques (where these use Pytorch)
- Assessments of both unlearning and of whether we've seen forgetting

**Comment by philswatton** [comment]
I've put in a request for 2500 hours on Baskerville

**Comment by philswatton** [comment]
We now have Baskerville. I've set up a conda env with the repo code installed.

**Comment by philswatton** [comment]
Closed as complete
